# Generated by Django 3.1.4 on 2021-03-23 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20210317_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_price', models.FloatField()),
                ('description', models.TextField()),
                ('image_1', models.ImageField(upload_to='static/images/post_img')),
                ('image_2', models.ImageField(upload_to='static/images/post_img')),
                ('image_3', models.ImageField(upload_to='static/images/post_img')),
                ('image_4', models.ImageField(upload_to='static/images/post_img')),
                ('image_5', models.ImageField(upload_to='static/images/post_img')),
                ('image_6', models.ImageField(upload_to='static/images/post_img')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
        ),
    ]
