# Generated by Django 3.1.4 on 2021-03-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210324_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookad',
            name='image_1',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='image_2',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='image_3',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='image_4',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='image_5',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='image_6',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
