# Generated by Django 3.1.4 on 2021-03-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210324_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookad',
            name='image_4',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='image_5',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='image_6',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
