# Generated by Django 3.1.4 on 2021-03-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210325_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookad',
            name='image_1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='image_2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='image_3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='image_4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='image_5',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookad',
            name='image_6',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
