# Generated by Django 3.1.4 on 2021-03-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210325_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookad',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='bookad',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='bookad',
            name='image_6',
        ),
    ]
