# Generated by Django 3.1.4 on 2021-04-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_messagebychat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageByChat',
        ),
    ]
