# Generated by Django 3.1.4 on 2021-04-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_delete_messagebychat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookad',
            name='upload_date',
        ),
    ]
