# Generated by Django 3.1.4 on 2021-04-08 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_bookad_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookad',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
