# Generated by Django 3.1.4 on 2021-04-05 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210325_1122'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_chat',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_user', to='posts.bookad'),
        ),
    ]
