# Generated by Django 3.1.4 on 2021-04-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210402_1130'),
        ('users', '0004_delete_users_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageByChat',
        ),
    ]
