# Generated by Django 3.1.4 on 2021-04-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210405_1332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageByChat',
        ),
    ]
