# Generated by Django 3.1.4 on 2021-03-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eBook_name', models.CharField(max_length=100)),
                ('eBook_author', models.CharField(max_length=100)),
                ('eBook_price', models.FloatField()),
                ('eBook_description', models.TextField()),
                ('eBook_image', models.ImageField(upload_to='static/images')),
                ('eBook_file', models.FileField(upload_to='staitc/file')),
                ('eBook_publisher', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('language', models.CharField(choices=[('english', 'english'), ('hindi', 'hindi'), ('gujrati', 'gujrati')], max_length=50)),
                ('file_size', models.CharField(max_length=100)),
                ('print_length', models.CharField(max_length=100)),
            ],
        ),
    ]
