# Generated by Django 3.1.4 on 2021-03-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0002_orderbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='book',
        ),
        migrations.AddField(
            model_name='orderbook',
            name='book_name',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='orderbook',
            name='book_price',
            field=models.FloatField(default='', editable=False),
        ),
    ]
