# Generated by Django 3.1.4 on 2021-03-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0003_auto_20210330_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='book_id',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='book_name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
