# Generated by Django 3.1.4 on 2021-03-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0004_auto_20210330_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='book_price',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
