# Generated by Django 3.1.4 on 2021-03-30 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0005_auto_20210330_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='book_id',
        ),
    ]
