# Generated by Django 3.1.4 on 2021-03-30 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210317_1135'),
        ('e_book', '0006_remove_orderbook_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdereBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=100)),
                ('price_book', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderBook',
        ),
    ]
