# Generated by Django 3.1.4 on 2021-03-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210317_1135'),
        ('e_book', '0007_auto_20210330_1055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdereBook',
            new_name='Bookorder',
        ),
    ]
