# Generated by Django 3.1.4 on 2021-04-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0008_auto_20210330_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookorder',
        ),
    ]
