# Generated by Django 3.1.4 on 2021-04-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0009_delete_bookorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='gener',
            field=models.CharField(default='gener', max_length=100),
        ),
    ]
