# Generated by Django 3.1.4 on 2021-04-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_book', '0010_ebook_gener'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='gener',
        ),
    ]
