# Generated by Django 3.1.4 on 2021-04-02 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bookstoreseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookStore_name', models.CharField(max_length=100)),
                ('topic_book', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
                ('image_3', models.ImageField(upload_to='')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('bookStoreSeller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bookstoreseller')),
            ],
        ),
    ]
