# Generated by Django 3.1.4 on 2021-04-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bookstoread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstoread',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='bookstoread',
            name='image_3',
        ),
    ]
